apiVersion: v1
kind: Pod
metadata:
  name: custom-app-pod
  labels:
    app: custom-app
spec:
  containers:
  - name: custom-app-container
    image: custom-app
    ports:
    - containerPort: 3000
    volumeMounts:
    - mountPath: /app/logs
      name: logs-volume
    imagePullPolicy: Never
  volumes:
  - name: logs-volume
    emptyDir: {}
  imagePullSecrets:
  - name: regcred