apiVersion: v1
kind: Service
metadata:
  name: custom-app-service
spec:
  type: ClusterIP
  selector:
    app: custom-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000